# Generated by Django 5.1.1 on 2025-08-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin/Staff')], default='student', max_length=20),
        ),
    ]
