# Generated by Django 5.1.1 on 2025-08-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_model_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
